### ISSUE TITLE
What is this... exactly?

### ISSUE THREAD

**Issue by DrKat123** [banana439monkey/test#1]
It's a batch file.
For what purposes?
Just askin :stuck_out_tongue:

**Comment by banana439monkey** [comment]
:tongue: Uhh... I was at a code club and I was just making a random thing to show to my code club teacher. :package: I'm the only one in the club with github. Asking that I could use notepad instead? Our school don't have it and to access this account I needed to sign into drive.

**Comment by DrKat123** [comment]
:P
